/*

 LEVEL1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 64 x 18
   Tile set      : D:\Projectes GameBoy\Pekoland\Tiles\levelTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define LEVEL_1Width 64
#define LEVEL_1Height 18
#define LEVEL_1Bank 0

extern unsigned char LEVEL_1[];

/* End of LEVEL1.H */
