/*

 LEVEL1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 128 x 32
   Tile set      : D:\Projectes GameBoy\SuperPepeToni\Tiles\mapTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Level1Width 128
#define Level1Height 32
#define Level1Bank 0

extern unsigned char Level1[];

/* End of LEVEL1.H */
